import localFont from "next/font/local";
import "./globals.css";
import Header from "../../components/Header";



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white layout h-full">
        <Header />
        <div className="relative">
        {children}
        </div>
        <div className="fixed w-full p-2 bg-orange-500 text-black text-center" style={{bottom:"0px"}}> we are under maintainence </div>
      </body>
    </html>
  );
}
  